#pragma once

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (192U * 1024U)
#define LV_TICK_CUSTOM 1
#define LV_TICK_CUSTOM_INCLUDE "Arduino.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())

#define LV_USE_BTN 1
#define LV_USE_BAR 1
#define LV_USE_LABEL 1
#define LV_USE_OBJ 1
#define LV_USE_SLIDER 1
#define LV_USE_FLEX 1
#define LV_USE_GRID 1
#define LV_USE_STYLE 1
#define LV_USE_TIMER 1

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_SIMSUN_16_CJK 1
