[env:esp32-s3-touch-lcd-4_3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_INCLUDE_SIMPLE
  -I include
lib_deps =
  lvgl/lvgl@8.3.11
  moononournation/GFX Library for Arduino@1.4.9
  tamctec/TAMC_GT911@^1.0.2
